### ISSUE TITLE
zepp Life里面更改步数成功，但是支付宝&微信都没有同步

### ISSUE THREAD

**Issue by rubnet** [matocool/motion-for-email#3]

**Comment by liuxianhao666** [comment]
我也是zepp Life改步数成功能同步的微信，但不能同步的支付宝，新注册的号也是一样。
eppLIfe在支付宝授权里面不是显示为（乐运动）

**Comment by rubnet** [comment]
> 新注册的号也是一样不行。我的在支付宝授权里面显示是ZeppLife，请问你注册ZeppLife时地址选的是中国大陆吗？

**Comment by rubnet** [comment]
> > 我也是zepp Life改步数成功能同步的微信，但不能同步的支付宝，新注册的号也是一样。 eppLIfe在支付宝授权里面不是显示为（乐运动）
> 
> 我这边只有（乐运动）


新注册的号也是一样不行。我的在支付宝授权里面显示是ZeppLife，请问你注册ZeppLife时地址选的是中国大陆吗？

**Comment by liuxianhao666** [comment]
是不是绑了手环之类的？有说这样可以。

**Comment by L-Moshang** [comment]
绑了手环的账号一直没影响，其他账号无论手机号还是邮箱类型的全部无法推送至支付宝

**Comment by rubnet** [comment]
> > > > 我也是zepp Life改步数成功能同步的微信，但不能同步的支付宝，新注册的号也是一样。 eppLIfe在支付宝授权里面不是显示为（乐运动）
> > > 
> > > 
> > > 我这边只有（乐运动）
> > 
> > 
> > 新注册的号也是一样不行。我的在支付宝授权里面显示是ZeppLife，请问你注册ZeppLife时地址选的是中国大陆吗？
> 
> 是

我换虚拟机注册的新号，可以同步了，怀疑把我设备注册的新号都拉黑了
