### ISSUE TITLE
zepp步数变了，支付宝还是不行

### ISSUE THREAD

**Issue by tmwhxn** [matocool/motion-for-email#8]
我发现在支付宝设置-隐私-个人授权管理-取消对zepp Life的授权，然后注销zeppLIfe账号，这个步骤操作完，在支付宝运动小程序里面第三方接入还是能看到zepp life，还是授权状态；

**Comment by tmwhxn** [comment]
破案了，老设备黑了，需要换设备注册。换新设备注册新号，可在老设备绑定支付宝。

**Comment by euzenlee** [comment]
> 破案了，老设备黑了，需要换设备注册。换新设备注册新号，可在老设备绑定支付宝。

这个“设备”，指的是手机吗？

**Comment by liuxianhao666** [comment]
> 破案了，老设备黑了，需要换设备注册。换新设备注册新号，可在老设备绑定支付宝。

换几个设备了，包括电脑模拟器，仍不行。你绑定手环了吗？

**Comment by euzenlee** [comment]
> > 破案了，老设备黑了，需要换设备注册。换新设备注册新号，可在老设备绑定支付宝。
> 
> 换几个设备了，包括电脑模拟器，仍不行。你绑定手环了吗？


我遇到过这个问题，绑定手环，换了几个zepp账号也不行，最后是在支付定里解除zepp的授权，在zeep里重新绑定才解决的。支付宝的路径是 我的-设置-隐私-个人信息授权管理，这个在READEM有提及的。
